// generated by Fast Light User Interface Designer (fluid) version 1.0100

#include "controlPanel.h"

inline void ControlPanel::cb_controlTab_i(Fl_Tabs*, void*) {
  changeTab();
}
void ControlPanel::cb_controlTab(Fl_Tabs* o, void* v) {
  ((ControlPanel*)(o->parent()->user_data()))->cb_controlTab_i(o,v);
}

inline void ControlPanel::cb_volCheckButton_i(Fl_Check_Button*, void*) {
  volMute();
}
void ControlPanel::cb_volCheckButton(Fl_Check_Button* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_volCheckButton_i(o,v);
}

inline void ControlPanel::cb_micCheckButton_i(Fl_Check_Button*, void*) {
  micMute();
}
void ControlPanel::cb_micCheckButton(Fl_Check_Button* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_micCheckButton_i(o,v);
}

inline void ControlPanel::cb_lightCheckButton_i(Fl_Check_Button*, void*) {
  lightMute();
}
void ControlPanel::cb_lightCheckButton(Fl_Check_Button* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_lightCheckButton_i(o,v);
}

inline void ControlPanel::cb_calibButton_i(Fl_Button*, void*) {
  doCalibration();
}
void ControlPanel::cb_calibButton(Fl_Button* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_calibButton_i(o,v);
}

inline void ControlPanel::cb_volSlider_i(Fl_Slider*, void*) {
  changeVol();
}
void ControlPanel::cb_volSlider(Fl_Slider* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_volSlider_i(o,v);
}

inline void ControlPanel::cb_micSlider_i(Fl_Slider*, void*) {
  changeMic();
}
void ControlPanel::cb_micSlider(Fl_Slider* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_micSlider_i(o,v);
}

inline void ControlPanel::cb_lightSlider_i(Fl_Slider*, void*) {
  changeLight();
}
void ControlPanel::cb_lightSlider(Fl_Slider* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_lightSlider_i(o,v);
}

inline void ControlPanel::cb_monthChoice_i(Fl_Choice*, void*) {
  changeMonth();
}
void ControlPanel::cb_monthChoice(Fl_Choice* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_monthChoice_i(o,v);
}

Fl_Menu_Item ControlPanel::menu_monthChoice[] = {
 {"January", 0,  0, 0, 0, 0, 0, 12, 56},
 {"February", 0,  0, 0, 0, 0, 0, 12, 56},
 {"March", 0,  0, 0, 0, 0, 0, 12, 56},
 {"April", 0,  0, 0, 0, 0, 0, 12, 56},
 {"May", 0,  0, 0, 0, 0, 0, 12, 56},
 {"June", 0,  0, 0, 0, 0, 0, 12, 56},
 {"July", 0,  0, 0, 0, 0, 0, 12, 56},
 {"August", 0,  0, 0, 0, 0, 0, 12, 56},
 {"September", 0,  0, 0, 0, 0, 0, 12, 56},
 {"October", 0,  0, 0, 0, 0, 0, 12, 56},
 {"November", 0,  0, 0, 0, 0, 0, 12, 56},
 {"December", 0,  0, 0, 0, 0, 0, 12, 56},
 {0}
};

inline void ControlPanel::cb_yearCounter_i(Fl_Counter*, void*) {
  changeYear();
}
void ControlPanel::cb_yearCounter(Fl_Counter* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_yearCounter_i(o,v);
}

inline void ControlPanel::cb_hourInput_i(Fl_Value_Input*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_hourInput(Fl_Value_Input* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_hourInput_i(o,v);
}

inline void ControlPanel::cb_minInput_i(Fl_Value_Input*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_minInput(Fl_Value_Input* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_minInput_i(o,v);
}

inline void ControlPanel::cb_secInput_i(Fl_Value_Input*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_secInput(Fl_Value_Input* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_secInput_i(o,v);
}

inline void ControlPanel::cb_plusButton_i(Fl_Button*, void*) {
  plusTime();
}
void ControlPanel::cb_plusButton(Fl_Button* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_plusButton_i(o,v);
}

inline void ControlPanel::cb_minusButton_i(Fl_Button*, void*) {
  minusTime();
}
void ControlPanel::cb_minusButton(Fl_Button* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_minusButton_i(o,v);
}

inline void ControlPanel::cb_criticalTrigger_i(Fl_Counter*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_criticalTrigger(Fl_Counter* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_criticalTrigger_i(o,v);
}

inline void ControlPanel::cb_runCommandCheck_i(Fl_Check_Button*, void*) {
  enableCommand();
}
void ControlPanel::cb_runCommandCheck(Fl_Check_Button* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_runCommandCheck_i(o,v);
}

inline void ControlPanel::cb_playSoundCheck_i(Fl_Check_Button*, void*) {
  enableSoundFile();
}
void ControlPanel::cb_playSoundCheck(Fl_Check_Button* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_playSoundCheck_i(o,v);
}

inline void ControlPanel::cb_systemBeepCheck_i(Fl_Check_Button*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_systemBeepCheck(Fl_Check_Button* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_systemBeepCheck_i(o,v);
}

inline void ControlPanel::cb_notifyCheck_i(Fl_Check_Button*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_notifyCheck(Fl_Check_Button* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_notifyCheck_i(o,v);
}

inline void ControlPanel::cb_suspendCheck_i(Fl_Check_Button*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_suspendCheck(Fl_Check_Button* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_suspendCheck_i(o,v);
}

inline void ControlPanel::cb_backlightCheck_i(Fl_Check_Button*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_backlightCheck(Fl_Check_Button* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_backlightCheck_i(o,v);
}

inline void ControlPanel::cb_commandButton_i(Fl_Button*, void*) {
  openCommand();
}
void ControlPanel::cb_commandButton(Fl_Button* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_commandButton_i(o,v);
}

#include <FL/Fl_Pixmap.H>
static const char *idata_fileopen[] = {
"16 13 6 1",
" \tc None",
".\tc #040404",
"+\tc #000000",
"@\tc #F3F704",
"#\tc #F3F7F3",
"$\tc #808304",
"         ...    ",
"        +   . + ",
"             .. ",
" ...        ... ",
".@#@.......     ",
".#@#@#@#@#.     ",
".@#@#@#@#@.     ",
".#@#@..........+",
".@#@.$$$$$$$$$+ ",
".#@.$$$$$$$$$.  ",
".@.$$$$$$$$$.   ",
"..$$$$$$$$$.    ",
"...........     "
};
static Fl_Pixmap image_fileopen(idata_fileopen);

inline void ControlPanel::cb_soundFileButton_i(Fl_Button*, void*) {
  openSoundFile();
}
void ControlPanel::cb_soundFileButton(Fl_Button* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_soundFileButton_i(o,v);
}

inline void ControlPanel::cb_netDeviceChoice_i(Fl_Choice*, void*) {
  changeNetDevice();
}
void ControlPanel::cb_netDeviceChoice(Fl_Choice* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_netDeviceChoice_i(o,v);
}

inline void ControlPanel::cb_hostNameInput_i(Fl_Input*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_hostNameInput(Fl_Input* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_hostNameInput_i(o,v);
}

inline void ControlPanel::cb_inetAddr0_i(Fl_Value_Input*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_inetAddr0(Fl_Value_Input* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_inetAddr0_i(o,v);
}

inline void ControlPanel::cb_inetAddr1_i(Fl_Value_Input*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_inetAddr1(Fl_Value_Input* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_inetAddr1_i(o,v);
}

inline void ControlPanel::cb_inetAddr2_i(Fl_Value_Input*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_inetAddr2(Fl_Value_Input* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_inetAddr2_i(o,v);
}

inline void ControlPanel::cb_inetAddr3_i(Fl_Value_Input*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_inetAddr3(Fl_Value_Input* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_inetAddr3_i(o,v);
}

inline void ControlPanel::cb_netMask0_i(Fl_Value_Input*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_netMask0(Fl_Value_Input* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_netMask0_i(o,v);
}

inline void ControlPanel::cb_netMask1_i(Fl_Value_Input*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_netMask1(Fl_Value_Input* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_netMask1_i(o,v);
}

inline void ControlPanel::cb_netMask2_i(Fl_Value_Input*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_netMask2(Fl_Value_Input* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_netMask2_i(o,v);
}

inline void ControlPanel::cb_netMask3_i(Fl_Value_Input*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_netMask3(Fl_Value_Input* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_netMask3_i(o,v);
}

inline void ControlPanel::cb_bcastAddr0_i(Fl_Value_Input*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_bcastAddr0(Fl_Value_Input* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_bcastAddr0_i(o,v);
}

inline void ControlPanel::cb_bcastAddr1_i(Fl_Value_Input*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_bcastAddr1(Fl_Value_Input* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_bcastAddr1_i(o,v);
}

inline void ControlPanel::cb_bcastAddr2_i(Fl_Value_Input*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_bcastAddr2(Fl_Value_Input* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_bcastAddr2_i(o,v);
}

inline void ControlPanel::cb_bcastAddr3_i(Fl_Value_Input*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_bcastAddr3(Fl_Value_Input* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_bcastAddr3_i(o,v);
}

inline void ControlPanel::cb_devInfoButton_i(Fl_Button*, void*) {
  showDevInfoDlg();
}
void ControlPanel::cb_devInfoButton(Fl_Button* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_devInfoButton_i(o,v);
}

inline void ControlPanel::cb_wifiDeviceChoice_i(Fl_Choice*, void*) {
  changeWifiDevice();
}
void ControlPanel::cb_wifiDeviceChoice(Fl_Choice* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_wifiDeviceChoice_i(o,v);
}

inline void ControlPanel::cb_wifiChannelChoice_i(Fl_Choice*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_wifiChannelChoice(Fl_Choice* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_wifiChannelChoice_i(o,v);
}

Fl_Menu_Item ControlPanel::menu_wifiChannelChoice[] = {
 {"1", 0,  0, 0, 0, 0, 0, 14, 56},
 {"2", 0,  0, 0, 0, 0, 0, 14, 56},
 {"3", 0,  0, 0, 0, 0, 0, 14, 56},
 {"4", 0,  0, 0, 0, 0, 0, 14, 56},
 {0}
};

inline void ControlPanel::cb_wifiModeChoice_i(Fl_Choice*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_wifiModeChoice(Fl_Choice* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_wifiModeChoice_i(o,v);
}

Fl_Menu_Item ControlPanel::menu_wifiModeChoice[] = {
 {"Auto", 0,  0, 0, 0, 0, 0, 14, 56},
 {"Ad-Hoc", 0,  0, 0, 0, 0, 0, 14, 56},
 {"Managed", 0,  0, 0, 0, 0, 0, 14, 56},
 {"Master", 0,  0, 0, 0, 0, 0, 14, 56},
 {"Repeater", 0,  0, 0, 0, 0, 0, 14, 56},
 {"Secondary", 0,  0, 0, 0, 0, 0, 14, 56},
 {0}
};

inline void ControlPanel::cb_essidInput_i(Fl_Input*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_essidInput(Fl_Input* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_essidInput_i(o,v);
}

inline void ControlPanel::cb_freqInput_i(Fl_Input*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_freqInput(Fl_Input* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_freqInput_i(o,v);
}

inline void ControlPanel::cb_rateInput_i(Fl_Input*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_rateInput(Fl_Input* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_rateInput_i(o,v);
}

inline void ControlPanel::cb_wifiInfoButton_i(Fl_Button*, void*) {
  showWifiInfoDlg();
}
void ControlPanel::cb_wifiInfoButton(Fl_Button* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_wifiInfoButton_i(o,v);
}

inline void ControlPanel::cb_baudRateChoice_i(Fl_Choice*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_baudRateChoice(Fl_Choice* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_baudRateChoice_i(o,v);
}

Fl_Menu_Item ControlPanel::menu_baudRateChoice[] = {
 {"9600", 0,  0, 0, 0, 0, 0, 14, 56},
 {"19200", 0,  0, 0, 0, 0, 0, 14, 56},
 {"38400", 0,  0, 0, 0, 0, 0, 14, 56},
 {"57600", 0,  0, 0, 0, 0, 0, 14, 56},
 {"115200", 0,  0, 0, 0, 0, 0, 14, 56},
 {"230400", 0,  0, 0, 0, 0, 0, 14, 56},
 {0}
};

inline void ControlPanel::cb_rs232CheckBox_i(Fl_Check_Button*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_rs232CheckBox(Fl_Check_Button* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_rs232CheckBox_i(o,v);
}

inline void ControlPanel::cb_enIrdaCheckBox_i(Fl_Check_Button*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_enIrdaCheckBox(Fl_Check_Button* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_enIrdaCheckBox_i(o,v);
}

inline void ControlPanel::cb_irdaModeCheckBox_i(Fl_Check_Button*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_irdaModeCheckBox(Fl_Check_Button* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_irdaModeCheckBox_i(o,v);
}

inline void ControlPanel::cb_dectCheckBox_i(Fl_Check_Button*, void*) {
  changeApplyButton();
}
void ControlPanel::cb_dectCheckBox(Fl_Check_Button* o, void* v) {
  ((ControlPanel*)(o->parent()->parent()->parent()->user_data()))->cb_dectCheckBox_i(o,v);
}

static const char *idata_tux_small[] = {
"131 144 256 2",
"  \tc None",
". \tc #020204",
"+ \tc #AC8409",
"@ \tc #444444",
"# \tc #EBC40C",
"$ \tc #835204",
"% \tc #C9A30B",
"& \tc #2A2204",
"* \tc #8E6A07",
"= \tc #B98309",
"- \tc #D0A40D",
"; \tc #A46D05",
"> \tc #B49306",
", \tc #02028F",
"\' \tc #362490",
") \tc #E4E4E4",
"! \tc #7E620C",
"~ \tc #D9B30D",
"{ \tc #654307",
"] \tc #C4C4C4",
"^ \tc #493006",
"/ \tc #F1D311",
"( \tc #A4770A",
"_ \tc #634581",
": \tc #CF9407",
"< \tc #936B50",
"[ \tc #885F07",
"} \tc #C78A08",
"| \tc #745307",
"1 \tc #141413",
"2 \tc #1D1588",
"3 \tc #ECB40B",
"4 \tc #A47846",
"5 \tc #B37907",
"6 \tc #413207",
"7 \tc #D2A851",
"8 \tc #9A770B",
"9 \tc #886049",
"0 \tc #BA8330",
"a \tc #DFA509",
"b \tc #B68C08",
"c \tc #A4A4A4",
"d \tc #32223C",
"e \tc #D19B09",
"f \tc #E6B33F",
"g \tc #EDCC0E",
"h \tc #483046",
"i \tc #F4D543",
"j \tc #B5B4B3",
"k \tc #5B3A05",
"l \tc #946C09",
"m \tc #0202D0",
"n \tc #744904",
"o \tc #EBBC0B",
"p \tc #A9782A",
"q \tc #838384",
"r \tc #1E165C",
"s \tc #B49654",
"t \tc #976105",
"u \tc #382605",
"v \tc #956B31",
"w \tc #F6D50D",
"x \tc #02024E",
"y \tc #4A3A0C",
"z \tc #463284",
"A \tc #6A4B06",
"B \tc #0F0ACA",
"C \tc #D7AC09",
"D \tc #685430",
"E \tc #AA7E0A",
"F \tc #1F15D1",
"G \tc #5B426F",
"H \tc #C08507",
"I \tc #A3713F",
"J \tc #906434",
"K \tc #D89C08",
"L \tc #B8A378",
"M \tc #EBCD28",
"N \tc #140D04",
"O \tc #906007",
"P \tc #E5AC09",
"Q \tc #C18B0A",
"R \tc #A5720A",
"S \tc #291C04",
"T \tc #392A0C",
"U \tc #F3C40B",
"V \tc #533606",
"W \tc #765460",
"X \tc #D7960D",
"Y \tc #B57E2F",
"Z \tc #F5BD0C",
"` \tc #949494",
" .\tc #BD9D04",
"..\tc #916544",
"+.\tc #0C0C0C",
"@.\tc #505050",
"#.\tc #F4F4F4",
"$.\tc #DEB45C",
"%.\tc #F2DA2C",
"&.\tc #AD780A",
"*.\tc #6E5A14",
"=.\tc #96720B",
"-.\tc #F1D42A",
";.\tc #827864",
">.\tc #F2B60C",
",.\tc #B67E0A",
"\'.\tc #3225BF",
").\tc #BEBDBC",
"!.\tc #281CCE",
"~.\tc #825A4B",
"{.\tc #D4D4D4",
"].\tc #C98E07",
"^.\tc #1C1C1B",
"/.\tc #F3CD0C",
"(.\tc #6A4644",
"_.\tc #CF9418",
":.\tc #A4843C",
"<.\tc #B48320",
"[.\tc #DAA309",
"}.\tc #C2930B",
"|.\tc #6C4505",
"1.\tc #4C3604",
"2.\tc #EBB316",
"3.\tc #9C7933",
"4.\tc #0202FC",
"5.\tc #402C07",
"6.\tc #5C4309",
"7.\tc #875805",
"8.\tc #E2BC0C",
"9.\tc #747474",
"0.\tc #5C5C5C",
"a.\tc #A2895C",
"b.\tc #646464",
"c.\tc #F2D28C",
"d.\tc #AA946C",
"e.\tc #6A529C",
"f.\tc #563E64",
"g.\tc #120CB4",
"h.\tc #ECECEC",
"i.\tc #563C92",
"j.\tc #9D774C",
"k.\tc #6E4D66",
"l.\tc #3C3C3C",
"m.\tc #261A84",
"n.\tc #8D8D8C",
"o.\tc #B8AD96",
"p.\tc #B79B5C",
"q.\tc #241971",
"r.\tc #2C2C2C",
"s.\tc #ACACAC",
"t.\tc #765234",
"u.\tc #402D9E",
"v.\tc #B58C35",
"w.\tc #3D2BB1",
"x.\tc #AE9C68",
"y.\tc #CCCCCC",
"z.\tc #DDDDDC",
"A.\tc #6C6C6B",
"B.\tc #AB8E47",
"C.\tc #906C6C",
"D.\tc #8A6C24",
"E.\tc #E8BD5E",
"F.\tc #DFAC42",
"G.\tc #7E5B5A",
"H.\tc #C8A24C",
"I.\tc #F6E2B4",
"J.\tc #C6B684",
"K.\tc #6B4A42",
"L.\tc #FEFEFC",
"M.\tc #2C1E54",
"N.\tc #3B2847",
"O.\tc #9C9C9C",
"P.\tc #7C7C7C",
"Q.\tc #52462C",
"R.\tc #AC8C04",
"S.\tc #5E4E34",
"T.\tc #5A46A4",
"U.\tc #343434",
"V.\tc #02022F",
"W.\tc #865E64",
"X.\tc #603E05",
"Y.\tc #784E04",
"Z.\tc #221AD4",
"`.\tc #7C5B0A",
" +\tc #C19C4E",
".+\tc #9A6A4C",
"++\tc #2C1C6C",
"@+\tc #0202B1",
"#+\tc #AC8E58",
"$+\tc #92825C",
"%+\tc #9E7E44",
"&+\tc #110CE9",
"*+\tc #6A4C84",
"=+\tc #F6DA14",
"-+\tc #97722E",
";+\tc #312305",
">+\tc #B0A58F",
",+\tc #8F5A04",
"\'+\tc #F6DA4A",
")+\tc #7D5A44",
"!+\tc #A77E30",
"~+\tc #E2BA64",
"{+\tc #020270",
"]+\tc #DAAA2C",
"^+\tc #1B13E1",
"/+\tc #A69B87",
"(+\tc #9B6605",
"_+\tc #553B06",
":+\tc #F5CD31",
"<+\tc #4A4A4C",
"[+\tc #8A6604",
"}+\tc #9E7E04",
"|+\tc #82723C",
"1+\tc #2A1EB4",
"2+\tc #5E3E2C",
"3+\tc #744E22",
"4+\tc #E1B40A",
"5+\tc #7D5305",
"6+\tc #1F1604",
"7+\tc #D6AE58",
"8+\tc #565654",
"9+\tc #987E34",
"0+\tc #A38E61",
"a+\tc #AD843A",
"b+\tc #F4EEDE",
"c+\tc #A27A64",
"d+\tc #4B34A4",
"e+\tc #8F645B",
"f+\tc #C29227",
"g+\tc #96766C",
"h+\tc #BFB5A4",
"i+\tc #5E4A04",
"j+\tc #8A7E64",
"k+\tc #91660A",
"l+\tc #92726C",
"m+\tc #8A665C",
"n+\tc #9C7248",
"o+\tc #392620",
"p+\tc #F6C62C",
"q+\tc #0A0604",
"r+\tc #9D6A07",
"s+\tc #BC9447",
"t+\tc #9C6D2D",
"u+\tc #C39A0E",
"v+\tc #C0AC90",
"w+\tc #5E5644",
"x+\tc #AB7205",
"y+\tc #CE8E08",
"z+\tc #76527C",
"A+\tc #342250",
"B+\tc #F6D630",
"C+\tc #EAC620",
"D+\tc #242424",
"E+\tc #A26E24",
"F+\tc #472F1F",
"G+\tc #B68A20",
"                                                                             \
                                                                              \
                                                                              \
                             ",
"                                                                             \
                                                                              \
                                                                              \
                             ",
"                                                                             \
                                                                              \
                                                                              \
                             ",
"                                                                             \
                                                                              \
                                                                              \
                             ",
"                                                                             \
                                                                              \
                                                                              \
                             ",
"                                                                             \
                                                                              \
                                                                              \
                             ",
"                                                                             \
                                                                              \
                                                                              \
                             ",
"                                                                             \
                                                                              \
                                                                              \
                             ",
"                                                                             \
                                                                              \
                                                                              \
                             ",
"                                                                             \
                                                                              \
                                                                              \
                             ",
"                                                                             \
                                                                              \
                                                                              \
                             ",
"                                                                             \
                                                                              \
                                                                              \
                             ",
"                                                                             \
                                                                              \
                                                                              \
                             ",
"                                                                             \
                                                                              \
                                                                              \
                             ",
"                                                                             \
                               . . . . . . . . .                              \
                                                                              \
                             ",
"                                                                             \
                             . . . . . . . . . . . .                          \
                                                                              \
                             ",
"                                                                             \
                       . . . . . . . . . . . . . . . . . .                    \
                                                                              \
                             ",
"                                                                             \
                       . . . . . . . . . . . . . . . . . . .                  \
                                                                              \
                             ",
"                                                                             \
                 . . . . . . . . . . . . . . . . . . q+q+. . . . .            \
                                                                              \
                             ",
"                                                                             \
                 . . . . . . . . . . . . . . . . . . D+r.^.+.. . . .          \
                                                                              \
                             ",
"                                                                             \
               . . . . . . . . . . . . . . . . . . +.l.@.<+U.q+. . .          \
                                                                              \
                             ",
"                                                                             \
               . . . . . . . . . . . . . . . . . . +.@ b.A.0.^.+.. . .        \
                                                                              \
                             ",
"                                                                             \
             . . . . . . . . . . . . . . . . . . . +.@.9.A.0.U.D+1 . . .      \
                                                                              \
                             ",
"                                                                             \
             . . . . . . . . . . . . . . . . . . . 1 @.b.8+@ r.D+1 q+. . .    \
                                                                              \
                             ",
"                                                                             \
           . . . . . . . . . . . . . . . . . . . . +.@ @ U.D+1 1 +.. . . .    \
                                                                              \
                             ",
"                                                                             \
           . . . . . . . . . . . . . . . . . . . . +.D+D+1 +.. . . . . . . .  \
                                                                              \
                             ",
"                                                                             \
         . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .  \
                                                                              \
                             ",
"                                                                             \
         . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .  \
                                                                              \
                             ",
"                                                                             \
         . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .  \
                                                                              \
                             ",
"                                                                             \
         . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\
                                                                              \
                             ",
"                                                                             \
         . . . q++.. . U.@ 1 . . . . . . . . . . . . . . U.b.. . . . . . . . .\
                                                                              \
                             ",
"                                                                             \
         . . . . . . . . +.@ ^.. . . . . . . . D+0.9.D+. . ^.. . . . . . . . .\
                                                                              \
                             ",
"                                                                             \
         . . . . 1 8+q ^.. ^.@ . . . . . . . r.P.n.O.s.` +.. D+. . . . . . . .\
                                                                              \
                             ",
"                                                                             \
         . . . ^.P.O.).` <+. . . . . . . . <+9.` c j ] y.O.1 q++.. . . . . . .\
                                                                              \
                             ",
"                                                                             \
         . . . q c ] z.z.] O.q+. . . . . 9.s.z.L.L.L.#.h.j P.. . . . . . . . .\
 .                                                                            \
                             ",
"                                                                             \
         . . . ).#.L.L.L.L.L.@.. . . . ^.).#.L.L.) ` L.L.L.{.. . . . . . . . .\
 .                                                                            \
                             ",
"                                                                             \
         . . . #.L.0.1 h.L.L.y.. . . . @ y.#.L.9.. +.l.L.L.L.+.. . . . . . . .\
 .                                                                            \
                             ",
"                                                                             \
         . . . #.P.. l.D+#.L.#.+.. +.q+@.{.L.L.. . r.b.U.#.L.^.. . . . . . . .\
 .                                                                            \
                             ",
"                                                                             \
         . . . L.. . . A.^.L.#.1 ^.r.l.@.{.L.h.. . . @ r.q L.` . . . . . . . .\
 .                                                                            \
                             ",
"                                                                             \
         . . . #.+.. . <+. L.h.. . . . +.s.#.) . . . . 1 b.L.c . . . . . . . .\
 .                                                                            \
                             ",
"                                                                             \
         . . . #.q+. . r.. #.A.;+1.5.;+q+0.h.h.. . . . . 9.L.O.. . . . . . . .\
 .                                                                            \
                             ",
"                                                                             \
         . . . #.^.. . . . o.E 4+P C 3 C =.O.#.. . . . . y.L.P.. . . . . . . .\
 .                                                                            \
                             ",
"                                                                             \
         . . . ) L.` . &.H &.4+o 8.8.~ + - # o }.S . r.#.L.L.. . . . . . . . .\
 .                                                                            \
                             ",
"                                                                             \
         . . . ] #.L.a.Q a 3 >.o 8.# # M :+/ /.U o C y.L.L.h.. . . . . . . . .\
 .                                                                            \
                             ",
"                                                                             \
         . . . @ {.s ,.K 4+3 >.o # g g %.%.\'+i w /.U C : :.|+. . . . . . . . \
. .                                                                           \
                              ",
"                                                                             \
         . . . +.* ,.H a P 3 o # # g / -.B+\'+B+w w w /./.o a +.. . . . . . . \
. .                                                                           \
                              ",
"                                                                             \
         . . . &.,.H : P 3 3 o # g g / \'+\'+B+=+w w =+w # ~ C+( q+. . . . . .\
 . . .                                                                        \
                               ",
"                                                                             \
           . +.5 H y+K 4+3 3 o # g M -.\'+w =+=+w w w ~ 8 ( [.`.. . . . . . . \
. . .                                                                         \
                              ",
"                                                                             \
           . +.5 H : [.3 3 o o g g -.i =+w =+=+w w g H : K K 6.. . . . . . . .\
 . .                                                                          \
                             ",
"                                                                             \
           . q+= ].K a o o o o g / i i =+=+w =+w - l : K K K i+. . . . . . . .\
 . . .                                                                        \
                             ",
"                                                                             \
           . . X.n * C o o Z g M / / w / g # l Q : X K K y+} . . . . 0.P.U.. .\
 . . .                                                                        \
                             ",
"                                                                             \
           . . ^.| 5+`.>.# /.M -./ / /  .! 5+5 : K K X } Y #+1 . . . r.P.q A.+\
.. . .                                                                        \
                             ",
"                                                                             \
           . . +.c D.[ | +  .%  .R.8 | &.= ].: : : : 0 J.] ).b.. . . +.b.q P.U\
.. . .                                                                        \
                             ",
"                                                                             \
           . . D+).).* &.( b > b Q Q ].y+y+y+y+} = ,.] y.] ).j . . . . D+q P.9\
.D+. . .                                                                      \
                             ",
"                                                                             \
         . . . U.).).).r+k+; H : : y+y+H H 5 ,.L ).h+).] {.z.).A.q+. . . U.b.U\
.. . . . .                                                                    \
                             ",
"                                                                             \
         . . . U.).).).).l O r+,.,.,.5 ; ; 5 0 ).h+j y.) h.#.h.] +.. . . . . .\
 . . . . .                                                                    \
                             ",
"                                                                             \
       . . . . U.).y.).h+).d.[ t t t t (+I p.).j ).] h.L.L.L.L.z.0.. . . . . .\
 . . . . . q+                                                                 \
                             ",
"                                                                             \
       . . . . <+) z.y.).).).).%+j.3.%+h+).).h+).] {.#.L.L.L.L.L.z.+.. . . . .\
 . . . . . q+                                                                 \
                             ",
"                                                                             \
       . . . . L.L.#.z.).).).).).).).).).).).] ) h.#.L.L.L.L.L.L.L.#.. . . . .\
 . . . . . . 1                                                                \
                             ",
"                                                                             \
     +.1 . . l.L.L.#.#.).).).).).).).).).).{.z.L.L.L.L.L.L.L.L.L.L.L.. . . . .\
 . . . . . . .                                                                \
                             ",
"                                                                             \
   . 1 +.. q+z.L.L.L.L.] ).).).).).).).] {.) #.L.L.L.L.L.L.L.L.L.L.L.1 . . . .\
 . . . . . . . .                                                              \
                             ",
"                                                                             \
 . . . +.. 9.L.L.L.L.L.z.).).).).).).).) h.L.L.L.L.L.L.L.L.L.L.L.L.L.9.q+. . .\
 . . . . . . . .                                                              \
                             ",
"                                                                            .\
 . . . . c L.L.L.L.L.L.L.L.#.) ) ) #.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.r.. . .\
 . . . . . . . . . .                                                          \
                             ",
"                                                                            .\
 . . . ^.L.L.L.L.L.L.L.L.L.L.#.#.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.O.+.. .\
 . . . . . . . . . . .                                                        \
                             ",
"                                                                          . .\
 . . . ).L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.h.. . .\
 . . . . . . . . . . .                                                        \
                             ",
"                                                                        . . .\
 . . . ) L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.#.#.. . .\
 . . . . . . . . . . .                                                        \
                             ",
"                                                                      . . . .\
 . . D+) #.L.L.L.L.L.L.L.L.L.L.#.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.#.h.#.O.q+.\
 . . . . . . . . . . . . .                                                    \
                             ",
"                                                                    . . . . .\
 . . ^.z.#.#.L.L.L.L.L.L.L.L.#.#.#.L.L.L.L.L.L.L.L.L.L.L.#.L.#.#.h.) h.h.z.+..\
 . . . . . . . . . . . . . .                                                  \
                             ",
"                                                                    . . . . .\
 . . @.] h.#.#.L.L.L.L.L.#.h.h.) h.#.#.L.L.L.L.L.L.#.#.#.#.#.h.) z.{.z.) h.+..\
 . . . . . . . . . . . . . . .                                                \
                             ",
"                                                                  . . . . . .\
 . +.q s.] z.h.#.#.#.#.#.) z.z.z.z.) h.L.L.L.#.L.#.) z.{.{.y.] y.y.] ] {.h.l..\
 . . . . . . . . . . . . . . .                                                \
                             ",
"                                                                . . . . . . .\
 +.^.O.s.] {.) #.L.L.L.L.L.L.) L.L.L.L.L.L.L.L.L.L.L.h.) z.{.] ] ).] ] ] ] ) 1\
 . . . @.D+. . . . . . . . . . .                                              \
                             ",
"                                                                . . . . . . .\
 1 1 c y.) #.L.L.L.L.L.L.L.#.h.L.L.L.L.L.L.L.L.L.L.L.L.L.L.#.) {.y.] ] ] ] {.z\
.. . . U.@ r.+.. . . . . . . . .                                              \
                             ",
"                                                              . . . . . . . .\
 D+A.).h.L.L.L.L.L.L.L.L.L.L.h.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.#.h.) y.] ] ] #\
.n.. . . . r.@ . . . . . . . . . .                                            \
                             ",
"                                                              . . . . +.r.. .\
 ^.] {.L.L.L.L.L.L.L.L.L.L.L.#.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.) {.y.] h\
.L.+.. . . . +.D+. . . . . . . . .                                            \
                             ",
"                                                              . . . @.+.. . ^\
.y.c s.c c c ` n.q n.n.` ` ` ` n.n.n.n.n.n.n.n.n.q q P.P.P.9.9.9.9.9.9.b.0.b.]\
 {.L.+.. . . . +.@ q+. . . . . . . .                                          \
                             ",
"                                                            . . . . @ . . . c\
 s.O.c c c c O.O.O.O.` ` ` ` O.` ` ` ` ` n.n.q P.9.A.0.b.0.0.@ @ @ @ @ U.r.r.O\
.{.#.j . . . 1 . D+r.. . . . . . . .                                          \
                             ",
"                                                            . . . . +.. . . #\
.O.c O.O.O.` n.q n.q q q q P.q q P.P.P.P.P.9.9.A.A.b.0.0.8+<+@ @.<+<+<+l.r.r.P\
.y.{.L.. . +.D+^.+.<+1 . . . . . . . .                                        \
                             ",
"                                                            . . . 1 . . . . L\
.c O.n.` ` P.9.A.A.A.9.9.A.b.b.A.A.A.A.A.A.A.A.A.b.b.b.0.8+<+U.@ @ @ q D+l.b.8\
+h.) #.. . 1 U.U.^.1 @ . . . . . . . .                                        \
                             ",
"                                                            . . 1 @ . . +.L.L\
.O.O.` n.c P.O.s.j s.j s.j j s.s.. . . s.j j j j j j j j j j @ @ @ @ @ r.D+r.^\
.{.L.L.+.1 D+l.r.^.. +.q+. . . . . . .                                        \
                             ",
"                                                            . . @ q+. . D+L.L\
.O.O.n.` O.P.O.s.s.s.s.s.s.s.s.. . . . . s.s.s.j j j s.s.s.j @ @ @ <+@ b.8+U.1\
 {.L.L.l.+.^.^.1 +.. . D+. . . . . . .                                        \
                             ",
"                                                          . . +.8+. . +.j L.L\
.O.` n.` O.P.O.s.s.j s.s.s.s.s.. +.. . . s.s.s.j j j s.s.s.j @ @ <+@ q n.P.9.^\
.O.L.L.c . . q+. . . . l.. . . . . . . .                                      \
                             ",
"                                                          . . U.^.. . 1 L.L.L\
.O.` q n.` 9.O.s.s.j s.s.s.s.s.. L.. L.. . s.s.j j s.s.s.s.j @ @ <+@ q q ` q 1\
 q L.L.h.. . . . . . . 8+. . . . . . . .                                      \
                             ",
"                                                        . . 1 @ . . 1 h.L.L.L\
.O.` n.n.n.9.` s.s.s.s.s.c c c . [.g =+. . s.s.s.s.s.c c c c @ @ <+@ 9.{.h.y.1\
 ).L.L.L.+.. . . . . . @.D+. . . . . . .                                      \
                             ",
"                                                        . . @ +.. . l.L.L.L.L\
.O.` q n.n.A.` s.s.s.s.s.c c c . k+g } . . s.s.s.s.s.c c c c @ @ @ @ @.8+b.l.@\
.h.L.L.L.r.. . . . . . <+^.. . . . . . . .                                    \
                             ",
"                                                      . . . 0.. . . ).L.L.L.L\
.O.` q n.n.9.` s.c s.s.c c c c . ).o.j . . +.s.s.s.c c c c c @ <+@ @ @ U.r.D+s\
.L.L.L.L.9.. . . . . . @.+.. . . . . . . .                                    \
                             ",
"                                                      . . . l.. . . #.L.L.L.L\
.O.` n.n.n.9.` s.c s.c c c c c L.L.#.L.L.. . s.s.c c c O.O.O.@ @ @ @ n.r.D+U.L\
.L.L.L.L.O.. . . . . . <++.. . . . . . . .                                    \
                             ",
"                                                    . . . . +.. . . L.L.L.L.L\
.O.O.n.q q A.n.c c c c O.O.O.. L.L.L.L.L.y.. . c c O.O.` ` ` @ @ @ @ @ U.r.^.L\
.L.L.L.L.{.. . . . . . @ . . . . . . . . .                                    \
                             ",
"                                                    . . . . q+. . +.L.L.L.L.L\
.O.` n.q q A.` c c c c O.O.O.1 L.L.L.L.L.L.q+8+c c O.O.` ` ` @ @ @ <+<+r.r.r.L\
.L.L.L.L.) . . . . . . @.. . . . . . . . . .                                  \
                             ",
"                                                  . . . . . +.. . 1 L.L.L.L.L\
.O.` q q P.A.n.c c c c O.O.. . L.#.L.L.L.L.. +.c O.O.O.` ` n.@ @ @ <+@ r.r.r.L\
.L.L.L.L.h.. . . . . . l.. . . . . . . . . .                                  \
                             ",
"                                                  . . . . . +.. . 1 L.L.L.L.L\
.O.O.n.q q b.n.c c c O.O.O.. . L.h.L.L.L.L.. q+c c O.O.O.` ` @ @ @ @ @ U.r.r.L\
.L.L.L.L.h.. . . . . . D+. . . . . . . . . .                                  \
                             ",
"                                                . . . . . . r.. . r.L.L.L.L.L\
.O.` q q q A.n.O.O.c O.H _.Z Z L.L.L.L.L.P N . c c c c c O.O.<+@ @ @ 9.r.D+r.L\
.L.L.L.L.#.. . . . . . q+. . . . . . . . . .                                  \
                             ",
"                                                . . . . . . b.. . l.L.L.L.<+1\
 . @ q q q A.q O.O.c c >.Z Z Z . L.L.L.L.X K ].>.c c c O.O.O.<+@ @ l.@.U.r.D+L\
.L.L.L.L.#.. . . . . . . . . . . . . . . . .                                  \
                             ",
"                                              . . . . . . . q . . b.@ <+U.. .\
 . U.@ P.P.A.q O.O.c c >.Z Z Z . L.L.L.L.: Z Z Z Z c O.O.` ` @ @ @ @ 0.D+D+r.L\
.L.L.L.L.#.. . . . . ^.. . . . . . . . . . .                                  \
                             ",
"                                              . . . . . . . . . . . . . . . .\
 . . @ P.P.A.q O.O.c c >.Z Z Z e #.L.L.. Q Z Z >.c c ` ` ` ` @ @ @ @ @ r.r.r.L\
.L.L.L.L.) . . . . . @ . . . . . . . . . . .                                  \
                             ",
"                                              . . . . . . . +.. . . . . . . .\
 . . . P.9.A.P.` ` O.O.O.O.O.^ ^ ` ` ` n.V r+{ ` ` ` ` n.n.n.<+@ l.@ l.r.D+r.L\
.L.L.L.L.s.. . . U.l.D+^.D+D++.. . . . . .                                    \
                             ",
"                                              . . . . . q+. . . . . . . . . .\
 . . . P.9.b.b.A.A.9.9.9.A.A.A.b.b.b.A.0.0.0.b.0.b.b.b.0.0.8+l.@ @ @ l.r.D+r.L\
.L.L.L.L.A.. . U.+.+.. +.+.^.D+r.^.q+. . .                                    \
                             ",
"                                                . N - >.o Q . . . . . . . . .\
 . . . 9.9.b.b.0.0.0.0.0.0.0.8+8+8+8+8+8+8+0.0.0.0.0.8+@.<+<+@ <+l.l.@ r.D+r.L\
.L.L.L.L.r.. D+. . . . . . . . ^.<+A.^.. .                                    \
                             ",
"                                                3+Q Z Z Z Z S . . . . . . . .\
 . . . 9.9.A.A.0.0.0.0.8+8+8+8+0.0.8+8+@.@.@.@.@.@.<+<+<+@ @ @ @ @ <+@ r.D+r.L\
.L.L.L.h.. 1 1 . . . . . . . . . 1 @.A.. .                                    \
                             ",
"                                              <._.P Z Z Z Z Z P T . . . . . .\
 . ^.A.9.9.b.b.0.0.0.8+@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.<+@ @ @ @ @ @ @ l.r.D+r.a\
 Z /./.Z >.6 . . . . . . . . . . r.l.D++.                                     \
                             ",
"                                              H K P Z Z Z Z Z Z C 1 . . . . .\
 c P.P.A.A.A.b.0.0.0.0.8+8+8+8+8+8+8+8+8+@.@.@.@.@.@.<+@ @ @ @ @ @ @ <+r.r.D+P\
 /.w =+w p+S . . . . . . . . . . D+^.1 u+8.                                   \
                             ",
"                                            H y+a P Z Z Z Z Z Z Z - . . . . L\
.) b.b.b.b.0.0.0.0.0.8+8+@.@.@.<+<+<+<+<+<+<+<+<+<+@ @ @ l.l.l.l.l.l.@ ^.D+1 a\
 >.Z /./.4+^.. . . . . . . . . 1 1 +.. o w w                                  \
                             ",
"                                            } K a 2.Z Z Z Z Z Z Z o . . . L.L\
.L.L.n.9.b.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.b.b.b.b.b.b.b.b.A.8+0.n.a\
 3 Z Z # }.^.. . . . . . . . . . . . N /./ w C                                \
                             ",
"                            = H Q Q = = = ].[.P 2.>.Z Z Z Z Z Z Z Z [.L.L.L.L\
.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.#.L.L.L.L.L.#.L.L.L.K\
 3 Z o C = S . . . . . . . . . . . V C o o Z o                                \
                             ",
"                          ,.K K [.[.e : : [.P 2.>.Z Z Z Z Z Z Z Z Z g }.L.L.L\
.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.#.L.L.L.L.) {.a\
 P >.>.a H |.q+. . . . . . . . . 6+: 4+3 >.Z >.                               \
                             ",
"                        ,._.a a P P a a P P 2.Z Z Z Z Z Z Z Z Z Z Z g 8.R L.L\
.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.#.L.L.L.L.L.L.L.{.] ] K\
 3 o 3 K H ( u q+. . . . . . . u H K 4+3 3 >.P                                \
                             ",
"                        = X P >.3 3 P P 3 >.Z Z Z Z Z Z Z Z Z Z Z Z U # - R L\
.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.#.L.L.L.L.L.) y.] ] K\
 P 3 3 K ].,.x+. . . . . . . S = : [.4+3 >.Z >.                               \
                             ",
"                      Y ].[.3 Z Z Z Z >.Z Z Z Z Z >.Z Z Z Z Z Z Z Z Z Z g C L\
.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.#.L.#.L.L.L.L.{.] ] ] X\
 a P 3 a K ].H ,.5 &.&.5 5 + H K P 3 o Z >.Z Z                                \
                             ",
"                      ,.} a >.>.Z Z Z Z Z >.Z Z Z >.Z Z Z Z Z Z Z Z o Z U # L\
.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.{.] ] ] _\
.a 3 3 P K : ].Q H = H } } : e P >.Z >.Z Z Z >.u+                             \
                             ",
"                        Q [.2.Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z /.[\
 L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.#.L.L.L.L.] ] ] ]\
.K P 3 P a K X : : : ].: : e a 3 Z Z Z Z Z Z >.4+                             \
                             ",
"                        H K 2.2.Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z /.e\
 L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.] ] ] Q\
 K P 3 3 P a K K X : : K K a P Z Z Z Z Z Z Z o >.C                            \
                             ",
"                        = X 3 >.Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z g\
 a R L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.] ] =\
 X a P >.3 3 P P P a a P P 3 3 Z Z Z Z Z Z Z Z Z >.>.a                        \
                             ",
"                        = _.P >.Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z g\
 # ].L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.] ` H\
 X a P >.>.>.3 P P P P 3 P 3 >.Z Z Z Z Z Z Z Z Z 2.>.Z                        \
                             ",
"                        ,.y+P 2.Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z o\
 /.4+E L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.{.] 1 =\
 X a P >.Z Z Z >.3 3 3 >.>.>.>.Z Z Z Z Z Z Z Z Z Z Z >.>.u+                   \
                             ",
"                        <._.P 2.Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z >.Z o\
 /./.[.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.b+).1 1 =\
 K a P >.>.Z Z Z Z Z >.>.Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z >.Z 2.p                \
                             ",
"                        H y+P >.Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z\
 Z # g ( L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.#.L.. . . S =\
 : a 3 >.Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z >.               \
                             ",
"                        H y+a >.Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z\
 Z o # e [ L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.#.P.. . . ;+=\
 K a 3 >.Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z >.               \
                             ",
"                        } y+P >.>.Z Z Z Z Z >.Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z\
 Z Z 8.~ } j+L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.#.U.. . . . 5.=\
 e a 3 Z >.Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z P                \
                             ",
"                        H y+P >.Z >.Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z\
 Z Z o # - R z.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.z.+.. . . . . ^ ,\
.: a >.Z >.Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z P P a                \
                             ",
"                      5 H : >.Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z\
 Z >.>.# 4+: R L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.P.. . . . . . . . X.,\
.e P >.Z >.Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z >.Z >.a X y+                 \
                             ",
"                      ,.} K Z >.Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z\
 Z >.Z 4+~ e E @ #.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.s.+.. . . . . . . . N 6.,\
.K P 3 Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z >.>.2.a _.Y                    \
                             ",
"                    ,.} X a Z >.Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z\
 Z Z Z 4+C - = S +.O.L.L.L.L.L.L.L.L.L.L.L.L.L.L.) A.. . . . . . . . . . 6+X.,\
.e a 3 >.Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z >.>.P a K X                        \
                             ",
"                    H } X a >.Z Z >.>.Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z\
 Z >.Z P C e = { N . +.s.z.#.L.#.#.#.L.#.) y.q +.. . . . . . . . . . . . S X.=\
 e a 3 Z Z Z Z Z Z Z Z Z Z Z Z Z Z >.>.Z Z 2.P K _.H E+                       \
                             ",
"                    ,.H y+K P P 3 2.>.>.>.Z Z >.Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z\
 Z Z >.3 [.K = Y.^ . . . . . . . . . . . . . . . . . . . . . . . . . . . 5.n ,\
.: [.P Z Z Z Z Z Z Z Z Z Z Z Z 2.2.3 2.a K : &.                               \
                             ",
"                    ,.H } ].K a a P P P P 3 2.>.>.>.>.>.>.Z Z Z Z Z Z Z Z Z Z\
 Z Z Z P K : 5 Y.V N . . . . . . . . . . . . . . . . . . . . . . . . . . ^ n ,\
.].[.P >.Z Z Z Z Z Z Z Z Z >.>.P a a [.].,.3+                                 \
                             ",
"                    5 5 = H } y+: X K K K a a P P 3 >.>.Z Z >.Z Z >.Z Z Z >.Z\
 Z Z >.a e } &.5+X.S . . . . . . . . . . . . . . . . . . . . . . . . . . ^ n 5\
 } X a >.Z >.Z Z >.>.>.>.>.2.P a K X y+7.                                     \
                             ",
"                      ; ; x+5 5 5 ,.} } y+y+: X K a P a P P Z Z Z Z Z Z Z >.>\
.Z Z >.K ].,.; Y.k S . . . . . . . . . . . . . . . . . . . . . . . . . . 5.{ x\
+H : K 3 >.>.>.Z >.>.>.>.P P a X y+} 5                                        \
                             ",
"                                    t (+x+x+5 x+5 5 ,.= = ].K K K a 2.>.2.>.>\
.3 P [.} 5 (+,+|.V 6+. . . . . . . . . . . . . . . . . . . . . . . . . . u k (\
+x+,.].a P P 3 3 3 P P K X y+} ; 5+                                           \
                             ",
"                                        $ 7.t t (+(+; ; &.5 = Q : X K K P P P\
 a K : ,.; ,+$ k ^ . . . . . .                               . . . . . . u V t\
 ; 5 H K K a a P a [.K ].H ,.x+2+                                             \
                             ",
"                                              A Y.$ ,+O t (+; 5 ,.= H ].: X :\
 y+H H t ,+$ n V S .                                                     u ^ ,\
+(+x+5 Q ].: : : : ].H ,.&.; [                                                \
                             ",
"                                                    k |.Y.$ O t (+r+x+5 5 ,.,\
.,.x+; $ $ n |.5.q+.                                                       ^ $\
 ,+; x+5 ,.= H = = ,.5 ; t 5+                                                 \
                             ",
"                                                                V { 5+5+7.$ $\
 $ $ $ |.X.V 5.                                                              V\
 |.$ ,+(+r+; ; ; ; (+,+|.                                                     \
                             ",
"                                                                    V X.{ |.n\
 n |.|.k V ^                                                                 5\
.^ k |.7.,+t t O 7.Y.{                                                        \
                             ",
"                                                                        ^ V X\
.k k V ^ 5.                                                                   \
 u 5.^ X.{ |.n { X.F+                                                         \
                             ",
"                                                                            5\
.5.u u                                                                        \
       5.5.5.5.                                                               \
                             ",
"                                                                             \
                                                                              \
                                                                              \
                             ",
"                                                                             \
                                                                              \
                                                                              \
                             ",
"                                                                             \
                                                                              \
                                                                              \
                             ",
"                                                                             \
                                                                              \
                                                                              \
                             ",
"                                                                             \
                                                                              \
                                                                              \
                             ",
"                                                                             \
                                                                              \
                                                                              \
                             ",
"                                                                             \
                                                                              \
                                                                              \
                             ",
"                                                                             \
                                                                              \
                                                                              \
                             ",
"                                                                             \
                                                                              \
                                                                              \
                             ",
"                                                                             \
                                                                              \
                                                                              \
                             "
};
static Fl_Pixmap image_tux_small(idata_tux_small);

inline void ControlPanel::cb_okayButton_i(Fl_Button*, void*) {
  doOkay();
}
void ControlPanel::cb_okayButton(Fl_Button* o, void* v) {
  ((ControlPanel*)(o->parent()->user_data()))->cb_okayButton_i(o,v);
}

inline void ControlPanel::cb_applyButton_i(Fl_Button*, void*) {
  doApply();
}
void ControlPanel::cb_applyButton(Fl_Button* o, void* v) {
  ((ControlPanel*)(o->parent()->user_data()))->cb_applyButton_i(o,v);
}

inline void ControlPanel::cb_cancelButton_i(Fl_Button*, void*) {
  doCancel();
}
void ControlPanel::cb_cancelButton(Fl_Button* o, void* v) {
  ((ControlPanel*)(o->parent()->user_data()))->cb_cancelButton_i(o,v);
}

inline void ControlPanel::cb_okayInfoButton_i(Fl_Button*, void*) {
  doInfoOkay();
}
void ControlPanel::cb_okayInfoButton(Fl_Button* o, void* v) {
  ((ControlPanel*)(o->parent()->user_data()))->cb_okayInfoButton_i(o,v);
}
#include<stdio.h>

ControlPanel::ControlPanel() {
  Fl_Window* w;
  { Fl_Window* o = controlWin = new Fl_Window(400, 300, "SIMpad Controlpanel");
    w = o;
    o->user_data((void*)(this));
    { Fl_Tabs* o = controlTab = new Fl_Tabs(10, 10, 381, 251);
      o->callback((Fl_Callback*)cb_controlTab);
      o->when(FL_WHEN_CHANGED);
      { Fl_Group* o = avGroup = new Fl_Group(10, 38, 380, 222, "A / V");
        o->labelsize(12);
        { Fl_Box* o = soundBoarder = new Fl_Box(20, 50, 165, 200);
          o->box(FL_BORDER_BOX);
        }
        { Fl_Box* o = videoBoarder = new Fl_Box(195, 50, 185, 200);
          o->box(FL_BORDER_BOX);
        }
        { Fl_Box* o = new Fl_Box(23, 40, 50, 20, "Audio:");
          o->box(FL_FLAT_BOX);
          o->labelsize(12);
        }
        { Fl_Box* o = new Fl_Box(200, 40, 50, 20, "Video:");
          o->box(FL_FLAT_BOX);
          o->labelsize(12);
        }
        { Fl_Check_Button* o = volCheckButton = new Fl_Check_Button(50, 225, 20, 20);
          o->down_box(FL_DOWN_BOX);
          o->callback((Fl_Callback*)cb_volCheckButton);
          o->when(FL_WHEN_CHANGED);
        }
        { Fl_Check_Button* o = micCheckButton = new Fl_Check_Button(122, 225, 20, 20);
          o->down_box(FL_DOWN_BOX);
          o->callback((Fl_Callback*)cb_micCheckButton);
          o->when(FL_WHEN_CHANGED);
        }
        { Fl_Check_Button* o = lightCheckButton = new Fl_Check_Button(234, 225, 20, 20);
          o->down_box(FL_DOWN_BOX);
          o->callback((Fl_Callback*)cb_lightCheckButton);
          o->when(FL_WHEN_CHANGED);
        }
        { Fl_Button* o = calibButton = new Fl_Button(280, 75, 80, 25, "Cali&bration");
          o->labelsize(12);
          o->callback((Fl_Callback*)cb_calibButton);
        }
        { Fl_Slider* o = volSlider = new Fl_Slider(46, 80, 28, 145, "Vol");
          o->type(4);
          o->selection_color(2);
          o->maximum(255);
          o->step(1);
          o->value(255);
          o->callback((Fl_Callback*)cb_volSlider);
          o->align(FL_ALIGN_TOP);
        }
        { Fl_Slider* o = micSlider = new Fl_Slider(118, 80, 28, 145, "Mic");
          o->type(4);
          o->selection_color(2);
          o->maximum(255);
          o->step(1);
          o->value(255);
          o->callback((Fl_Callback*)cb_micSlider);
          o->align(FL_ALIGN_TOP);
        }
        { Fl_Slider* o = lightSlider = new Fl_Slider(231, 80, 28, 145, "Light");
          o->type(4);
          o->selection_color(2);
          o->maximum(255);
          o->step(1);
          o->value(255);
          o->callback((Fl_Callback*)cb_lightSlider);
          o->align(FL_ALIGN_TOP);
        }
        o->end();
      }
      { Fl_Group* o = timeGroup = new Fl_Group(10, 38, 380, 222, "Time");
        o->labelsize(12);
        o->hide();
        { Fl_Box* o = dateBoarder = new Fl_Box(20, 50, 200, 200);
          o->box(FL_BORDER_BOX);
        }
        { Fl_Box* o = timeBoarder = new Fl_Box(230, 50, 150, 200);
          o->box(FL_BORDER_BOX);
        }
        { Fl_Choice* o = monthChoice = new Fl_Choice(28, 60, 95, 20);
          o->down_box(FL_BORDER_BOX);
          o->callback((Fl_Callback*)cb_monthChoice);
          o->align(132);
          o->when(FL_WHEN_CHANGED);
          o->menu(menu_monthChoice);
        }
        { Fl_Counter* o = yearCounter = new Fl_Counter(130, 60, 85, 20);
          o->type(1);
          o->labelsize(12);
          o->minimum(0);
          o->maximum(9999);
          o->step(1);
          o->value(2027);
          o->callback((Fl_Callback*)cb_yearCounter);
        }
        { Fl_Box* o = dateLabel = new Fl_Box(25, 40, 45, 20, "Date:");
          o->box(FL_FLAT_BOX);
          o->labelsize(12);
        }
        { Fl_Box* o = timeLabel = new Fl_Box(235, 40, 45, 20, "Time:");
          o->box(FL_FLAT_BOX);
          o->labelsize(12);
        }
        { Fl_Clock* o = sysClock = new Fl_Clock(240, 69, 130, 130);
          o->box(FL_ROUND_UP_BOX);
        }
        { Fl_Value_Input* o = hourInput = new Fl_Value_Input(245, 215, 25, 25);
          o->maximum(23);
          o->step(1);
          o->value(23);
          o->callback((Fl_Callback*)cb_hourInput);
        }
        { Fl_Value_Input* o = minInput = new Fl_Value_Input(283, 215, 25, 25);
          o->maximum(59);
          o->step(1);
          o->value(59);
          o->callback((Fl_Callback*)cb_minInput);
        }
        { Fl_Value_Input* o = secInput = new Fl_Value_Input(318, 215, 25, 25);
          o->maximum(59);
          o->step(1);
          o->value(59);
          o->callback((Fl_Callback*)cb_secInput);
        }
        { Fl_Button* o = plusButton = new Fl_Button(347, 215, 20, 12, "+");
          o->labelsize(10);
          o->callback((Fl_Callback*)cb_plusButton);
          o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
        }
        { Fl_Button* o = minusButton = new Fl_Button(347, 228, 20, 12, "-");
          o->labelsize(10);
          o->callback((Fl_Callback*)cb_minusButton);
          o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = calendarBox = new Fl_Box(28, 89, 185, 152);
          o->box(FL_DOWN_BOX);
          o->color(7);
          o->align(FL_ALIGN_CLIP);
        }
        { Fl_Box* o = new Fl_Box(30, 91, 25, 20, "M");
          o->box(FL_FLAT_BOX);
          o->color(30);
          o->labelsize(12);
          o->labelcolor(17);
        }
        { Fl_Box* o = new Fl_Box(56, 91, 25, 20, "T");
          o->box(FL_FLAT_BOX);
          o->color(30);
          o->labelsize(12);
          o->labelcolor(17);
        }
        { Fl_Box* o = new Fl_Box(82, 91, 25, 20, "W");
          o->box(FL_FLAT_BOX);
          o->color(30);
          o->labelsize(12);
          o->labelcolor(17);
        }
        { Fl_Box* o = new Fl_Box(108, 91, 25, 20, "T");
          o->box(FL_FLAT_BOX);
          o->color(30);
          o->labelsize(12);
          o->labelcolor(17);
        }
        { Fl_Box* o = new Fl_Box(134, 91, 25, 20, "F");
          o->box(FL_FLAT_BOX);
          o->color(30);
          o->labelsize(12);
          o->labelcolor(17);
        }
        { Fl_Box* o = new Fl_Box(160, 91, 25, 20, "S");
          o->box(FL_FLAT_BOX);
          o->color(30);
          o->labelsize(12);
          o->labelcolor(17);
        }
        { Fl_Box* o = new Fl_Box(186, 91, 25, 20, "S");
          o->box(FL_FLAT_BOX);
          o->color(30);
          o->labelsize(12);
          o->labelcolor(1);
        }
        new Fl_Button(30, 113, 25, 18, "31");
        new Fl_Button(30, 149, 25, 18, "31");
        new Fl_Button(30, 167, 25, 18, "31");
        new Fl_Button(30, 185, 25, 18, "31");
        new Fl_Button(30, 203, 25, 18, "31");
        new Fl_Button(30, 221, 25, 18, "31");
        new Fl_Button(30, 131, 25, 18, "31");
        new Fl_Button(82, 113, 25, 18, "31");
        new Fl_Button(108, 113, 25, 18, "31");
        new Fl_Button(134, 113, 25, 18, "31");
        new Fl_Button(160, 113, 25, 18, "31");
        new Fl_Button(186, 113, 25, 18, "31");
        new Fl_Button(56, 113, 25, 18, "31");
        o->end();
      }
      { Fl_Group* o = powerGroup = new Fl_Group(10, 38, 380, 222, "Power");
        o->labelsize(12);
        o->hide();
        { Fl_Box* o = new Fl_Box(155, 155, 225, 95);
          o->box(FL_BORDER_BOX);
        }
        { Fl_Progress* o = batteryState = new Fl_Progress(170, 190, 200, 25);
          o->selection_color(2);
        }
        { Fl_Counter* o = criticalTrigger = new Fl_Counter(155, 50, 50, 25);
          o->type(1);
          o->minimum(0);
          o->maximum(9999);
          o->step(1);
          o->value(5);
          o->callback((Fl_Callback*)cb_criticalTrigger);
          o->align(FL_ALIGN_LEFT);
        }
        { Fl_Check_Button* o = runCommandCheck = new Fl_Check_Button(25, 85, 20, 25, "Run command:");
          o->down_box(FL_DOWN_BOX);
          o->labelsize(13);
          o->callback((Fl_Callback*)cb_runCommandCheck);
          o->align(FL_ALIGN_RIGHT);
          o->when(FL_WHEN_CHANGED);
        }
        { Fl_Check_Button* o = playSoundCheck = new Fl_Check_Button(25, 110, 20, 25, "Play sound:");
          o->down_box(FL_DOWN_BOX);
          o->labelsize(13);
          o->callback((Fl_Callback*)cb_playSoundCheck);
          o->align(FL_ALIGN_RIGHT);
          o->when(FL_WHEN_CHANGED);
        }
        { Fl_Check_Button* o = systemBeepCheck = new Fl_Check_Button(25, 150, 20, 25, "System beep");
          o->down_box(FL_DOWN_BOX);
          o->labelsize(13);
          o->callback((Fl_Callback*)cb_systemBeepCheck);
          o->align(FL_ALIGN_RIGHT);
        }
        { Fl_Check_Button* o = notifyCheck = new Fl_Check_Button(25, 175, 20, 25, "Notify");
          o->down_box(FL_DOWN_BOX);
          o->labelsize(13);
          o->callback((Fl_Callback*)cb_notifyCheck);
          o->align(FL_ALIGN_RIGHT);
        }
        { Fl_Check_Button* o = suspendCheck = new Fl_Check_Button(25, 200, 20, 25, "Suspend");
          o->down_box(FL_DOWN_BOX);
          o->labelsize(13);
          o->callback((Fl_Callback*)cb_suspendCheck);
          o->align(FL_ALIGN_RIGHT);
        }
        { Fl_Check_Button* o = backlightCheck = new Fl_Check_Button(25, 225, 20, 25, "Backlight");
          o->down_box(FL_DOWN_BOX);
          o->labelsize(13);
          o->callback((Fl_Callback*)cb_backlightCheck);
          o->align(FL_ALIGN_RIGHT);
        }
        commandInput = new Fl_Input(155, 85, 195, 25);
        soundFileInput = new Fl_Input(155, 111, 195, 25);
        { Fl_Box* o = new Fl_Box(25, 50, 105, 25, "Critical Trigger:");
          o->labelsize(13);
        }
        { Fl_Button* o = commandButton = new Fl_Button(355, 85, 25, 25);
          o->image(image_fileopen);
          o->callback((Fl_Callback*)cb_commandButton);
        }
        { Fl_Button* o = soundFileButton = new Fl_Button(355, 111, 25, 25);
          o->image(image_fileopen);
          o->callback((Fl_Callback*)cb_soundFileButton);
        }
        { Fl_Box* o = new Fl_Box(160, 145, 105, 20, "Battery State:");
          o->box(FL_FLAT_BOX);
          o->labelsize(12);
        }
        { Fl_Box* o = new Fl_Box(330, 215, 40, 25, "good");
          o->labelsize(12);
        }
        { Fl_Box* o = new Fl_Box(170, 215, 40, 25, "min.");
          o->labelsize(12);
        }
        { Fl_Box* o = new Fl_Box(250, 215, 40, 25, "weak");
          o->labelsize(12);
        }
        o->end();
      }
      { Fl_Group* o = networkGroup = new Fl_Group(10, 38, 380, 222, "Network");
        o->labelsize(12);
        o->hide();
        { Fl_Box* o = netDeviceLabel = new Fl_Box(20, 55, 70, 25, "Device:");
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Choice* o = netDeviceChoice = new Fl_Choice(105, 55, 80, 25);
          o->down_box(FL_BORDER_BOX);
          o->callback((Fl_Callback*)cb_netDeviceChoice);
          o->when(FL_WHEN_CHANGED);
        }
        { Fl_Input* o = hostNameInput = new Fl_Input(275, 55, 105, 25, "Hostname:");
          o->callback((Fl_Callback*)cb_hostNameInput);
        }
        { Fl_Box* o = hwAddrLabel = new Fl_Box(20, 100, 70, 25, "HwAddr:");
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = hwAddrBox = new Fl_Box(105, 100, 155, 25);
          o->box(FL_DOWN_BOX);
        }
        { Fl_Box* o = inetAddrLabel = new Fl_Box(20, 140, 70, 25, "InetAddr:");
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = netMaskLabel = new Fl_Box(20, 177, 70, 25, "Netmask:");
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = bcastAddrLabel = new Fl_Box(20, 215, 70, 25, "Broadcast:");
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Value_Input* o = inetAddr0 = new Fl_Value_Input(105, 140, 35, 25);
          o->maximum(255);
          o->step(1);
          o->callback((Fl_Callback*)cb_inetAddr0);
        }
        { Fl_Value_Input* o = inetAddr1 = new Fl_Value_Input(145, 140, 35, 25);
          o->maximum(255);
          o->step(1);
          o->callback((Fl_Callback*)cb_inetAddr1);
        }
        { Fl_Value_Input* o = inetAddr2 = new Fl_Value_Input(185, 140, 35, 25);
          o->maximum(255);
          o->step(1);
          o->callback((Fl_Callback*)cb_inetAddr2);
        }
        { Fl_Value_Input* o = inetAddr3 = new Fl_Value_Input(225, 140, 35, 25);
          o->maximum(255);
          o->step(1);
          o->callback((Fl_Callback*)cb_inetAddr3);
        }
        { Fl_Value_Input* o = netMask0 = new Fl_Value_Input(105, 177, 35, 25);
          o->maximum(255);
          o->step(1);
          o->callback((Fl_Callback*)cb_netMask0);
        }
        { Fl_Value_Input* o = netMask1 = new Fl_Value_Input(145, 177, 35, 25);
          o->maximum(255);
          o->step(1);
          o->callback((Fl_Callback*)cb_netMask1);
        }
        { Fl_Value_Input* o = netMask2 = new Fl_Value_Input(185, 177, 35, 25);
          o->maximum(255);
          o->step(1);
          o->callback((Fl_Callback*)cb_netMask2);
        }
        { Fl_Value_Input* o = netMask3 = new Fl_Value_Input(225, 177, 35, 25);
          o->maximum(255);
          o->step(1);
          o->callback((Fl_Callback*)cb_netMask3);
        }
        { Fl_Value_Input* o = bcastAddr0 = new Fl_Value_Input(105, 215, 35, 25);
          o->maximum(255);
          o->step(1);
          o->callback((Fl_Callback*)cb_bcastAddr0);
        }
        { Fl_Value_Input* o = bcastAddr1 = new Fl_Value_Input(145, 215, 35, 25);
          o->maximum(255);
          o->step(1);
          o->callback((Fl_Callback*)cb_bcastAddr1);
        }
        { Fl_Value_Input* o = bcastAddr2 = new Fl_Value_Input(185, 215, 35, 25);
          o->maximum(255);
          o->step(1);
          o->callback((Fl_Callback*)cb_bcastAddr2);
        }
        { Fl_Value_Input* o = bcastAddr3 = new Fl_Value_Input(225, 215, 35, 25);
          o->maximum(255);
          o->step(1);
          o->callback((Fl_Callback*)cb_bcastAddr3);
        }
        { Fl_Button* o = devInfoButton = new Fl_Button(305, 215, 70, 25, "&Info");
          o->callback((Fl_Callback*)cb_devInfoButton);
        }
        o->end();
      }
      { Fl_Group* o = wirelessGroup = new Fl_Group(10, 38, 380, 222, "Wireless");
        o->labelsize(12);
        o->hide();
        { Fl_Choice* o = wifiDeviceChoice = new Fl_Choice(101, 55, 75, 25);
          o->down_box(FL_BORDER_BOX);
          o->callback((Fl_Callback*)cb_wifiDeviceChoice);
          o->when(FL_WHEN_CHANGED);
        }
        { Fl_Choice* o = wifiChannelChoice = new Fl_Choice(101, 100, 75, 25);
          o->down_box(FL_BORDER_BOX);
          o->callback((Fl_Callback*)cb_wifiChannelChoice);
          o->when(FL_WHEN_CHANGED);
          o->menu(menu_wifiChannelChoice);
        }
        { Fl_Choice* o = wifiModeChoice = new Fl_Choice(101, 150, 75, 25);
          o->down_box(FL_BORDER_BOX);
          o->callback((Fl_Callback*)cb_wifiModeChoice);
          o->when(FL_WHEN_CHANGED);
          o->menu(menu_wifiModeChoice);
        }
        { Fl_Input* o = essidInput = new Fl_Input(286, 55, 85, 25, "ESSID:");
          o->callback((Fl_Callback*)cb_essidInput);
          o->when(FL_WHEN_CHANGED);
        }
        { Fl_Input* o = freqInput = new Fl_Input(286, 100, 85, 25, "Freq.:");
          o->callback((Fl_Callback*)cb_freqInput);
        }
        { Fl_Input* o = rateInput = new Fl_Input(286, 150, 85, 25, "Rate:");
          o->callback((Fl_Callback*)cb_rateInput);
        }
        { Fl_Box* o = wifiDeviceLabel = new Fl_Box(26, 55, 60, 25, "Device:");
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = wifiChannelLabel = new Fl_Box(26, 100, 60, 25, "Channel:");
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = wifiModeLabel = new Fl_Box(26, 150, 60, 25, "Mode:");
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Button* o = wifiInfoButton = new Fl_Button(300, 225, 80, 25, "&Info");
          o->callback((Fl_Callback*)cb_wifiInfoButton);
        }
        o->end();
      }
      { Fl_Group* o = cs3Group = new Fl_Group(10, 38, 380, 222, "CS3");
        o->labelsize(12);
        o->hide();
        { Fl_Box* o = rs232Boarder = new Fl_Box(20, 61, 360, 45, "RS232:");
          o->box(FL_BORDER_BOX);
          o->align(FL_ALIGN_TOP_LEFT);
        }
        { Fl_Choice* o = baudRateChoice = new Fl_Choice(280, 71, 90, 25, "Baud Rate:");
          o->down_box(FL_BORDER_BOX);
          o->callback((Fl_Callback*)cb_baudRateChoice);
          o->menu(menu_baudRateChoice);
        }
        { Fl_Box* o = irdaBoarder = new Fl_Box(20, 131, 360, 45, "IrDA:");
          o->box(FL_BORDER_BOX);
          o->align(FL_ALIGN_TOP_LEFT);
        }
        { Fl_Box* o = miscBoarder = new Fl_Box(20, 201, 360, 45, "Misc:");
          o->box(FL_BORDER_BOX);
          o->align(FL_ALIGN_TOP_LEFT);
        }
        { Fl_Check_Button* o = rs232CheckBox = new Fl_Check_Button(115, 74, 20, 20);
          o->down_box(FL_DOWN_BOX);
          o->callback((Fl_Callback*)cb_rs232CheckBox);
        }
        { Fl_Check_Button* o = enIrdaCheckBox = new Fl_Check_Button(115, 143, 20, 20);
          o->down_box(FL_DOWN_BOX);
          o->callback((Fl_Callback*)cb_enIrdaCheckBox);
        }
        { Fl_Check_Button* o = irdaModeCheckBox = new Fl_Check_Button(280, 143, 20, 20, "IrDA Mode:");
          o->down_box(FL_DOWN_BOX);
          o->callback((Fl_Callback*)cb_irdaModeCheckBox);
          o->align(FL_ALIGN_LEFT);
        }
        { Fl_Check_Button* o = greeLedCheckBox = new Fl_Check_Button(115, 213, 20, 20, "Green LED:");
          o->down_box(FL_DOWN_BOX);
          o->align(FL_ALIGN_LEFT);
          o->deactivate();
        }
        { Fl_Check_Button* o = dectCheckBox = new Fl_Check_Button(280, 214, 20, 20, "Dect:");
          o->down_box(FL_DOWN_BOX);
          o->callback((Fl_Callback*)cb_dectCheckBox);
          o->align(FL_ALIGN_LEFT);
        }
        { Fl_Box* o = new Fl_Box(30, 73, 55, 20, "Enable:");
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = new Fl_Box(30, 143, 55, 20, "Enable:");
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        o->end();
      }
      { Fl_Group* o = infoGroup = new Fl_Group(10, 38, 380, 222, "Info");
        o->color(28);
        o->labelsize(12);
        o->hide();
        { Fl_Box* o = new Fl_Box(25, 50, 163, 30, "SIMpad with Linux:");
          o->labeltype(FL_ENGRAVED_LABEL);
          o->labelsize(16);
          o->labelcolor(4);
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = new Fl_Box(25, 74, 162, 2);
          o->box(FL_DOWN_BOX);
          o->color(4);
          o->selection_color(4);
          o->labelcolor(4);
        }
        { Fl_Box* o = new Fl_Box(25, 85, 90, 25, "Bootloader:");
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = bootloaderBox = new Fl_Box(115, 85, 155, 25, "....");
          o->labelcolor(80);
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = new Fl_Box(25, 110, 70, 25, "CPU Info:");
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = cpuInfoBox = new Fl_Box(115, 110, 155, 25, "....");
          o->labelcolor(80);
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = new Fl_Box(25, 135, 60, 25, "Kernel:");
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = kernelBox = new Fl_Box(115, 135, 155, 25, "....");
          o->labelcolor(80);
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = new Fl_Box(25, 160, 60, 25, "Gcc:");
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = glibcBox = new Fl_Box(115, 160, 155, 25, "....");
          o->labelcolor(80);
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = tuxIcon = new Fl_Box(275, 40, 115, 140);
          o->image(image_tux_small);
        }
        { Fl_Box* o = new Fl_Box(25, 190, 90, 20, "Homepage:");
          o->labelsize(11);
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = new Fl_Box(105, 210, 160, 20, "messi At sourceforge.net");
          o->labelsize(12);
          o->labelcolor(4);
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = new Fl_Box(25, 210, 90, 20, "Contact:");
          o->labelsize(11);
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = new Fl_Box(105, 190, 160, 20, "simpad.sourceforge.net");
          o->labelsize(12);
          o->labelcolor(4);
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = new Fl_Box(25, 235, 303, 20, "(c) 2002, J\374rgen Messerer, Version 0.1, License: GPL");
          o->labelsize(10);
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        o->end();
      }
      o->end();
    }
    { Fl_Button* o = okayButton = new Fl_Button(10, 270, 80, 25, "&Okay");
      o->callback((Fl_Callback*)cb_okayButton);
    }
    { Fl_Button* o = applyButton = new Fl_Button(165, 271, 80, 25, "&Apply");
      o->callback((Fl_Callback*)cb_applyButton);
    }
    { Fl_Button* o = cancelButton = new Fl_Button(310, 270, 80, 25, "&Cancel");
      o->callback((Fl_Callback*)cb_cancelButton);
    }
    o->end();
  }
  { Fl_Window* o = infoDlgWin = new Fl_Window(480, 200, "Infodialog of net device");
    w = o;
    o->user_data((void*)(this));
    { Fl_Output* o = infoDevOutput = new Fl_Output(10, 10, 460, 155);
      o->type(12);
      o->align(132);
    }
    { Fl_Button* o = okayInfoButton = new Fl_Button(10, 170, 460, 25, "&Dismiss");
      o->callback((Fl_Callback*)cb_okayInfoButton);
    }
    o->set_modal();
    o->end();
  }
}

void ControlPanel::doOkay() {
  printf("Virtual:doOkay()!\n");
}

void ControlPanel::doApply() {
  printf("Virtual:doApply()!\n");
}

void ControlPanel::doCancel() {
  printf("Virtual:doCancel()!\n");
}

void ControlPanel::changeTab() {
  printf("Virtual:changeTab()!\n");
}

void ControlPanel::changeVol() {
  printf("Virtual:changeVol()!\n");
}

void ControlPanel::changeMic() {
  printf("Virtual:changeMic()!\n");
}

void ControlPanel::changeLight() {
  printf("Virtual:changeLight()!\n");
}

void ControlPanel::volMute() {
  printf("Virtual:volMute()!\n");
}

void ControlPanel::micMute() {
  printf("Virtual:micMute()!\n");
}

void ControlPanel::lightMute() {
  printf("Virtual:lightMute()!\n");
}

void ControlPanel::doCalibration() {
  printf("Virtual:doCalibration()!\n");
}

void ControlPanel::show( int argc, char** argv) {
  controlWin->show();
}

void ControlPanel::changeMonth() {
  printf("Virtual:changeMonth()!\n");
}

void ControlPanel::changeYear() {
  printf("Virtual:changeYear()!\n");
}

void ControlPanel::plusTime() {
  printf("Virtual:plusTime()!\n");
}

void ControlPanel::minusTime() {
  printf("Virtual:minusTime()!\n");
}

void ControlPanel::openCommand() {
  printf("Virtual:openCommand()!\n");
}

void ControlPanel::openSoundFile() {
  printf("Virtual:openSoundFile()!\n");
}

void ControlPanel::enableCommand() {
  printf("Virtual:enableCommand()!\n");
}

void ControlPanel::enableSoundFile() {
  printf("Virtual:enableSoundFile()!\n");
}

void ControlPanel::changeNetDevice() {
  printf("Virtual:changeNetDevice()!\n");
}

void ControlPanel::showDevInfoDlg() {
  printf("Virtual:showDevInfoDlg()!\n");
}

void ControlPanel::changeWifiDevice() {
  printf("Virtual:changeWifiDevice()!\n");
}

void ControlPanel::showWifiInfoDlg() {
  printf("Virtual:showWifiInfoDlg()!\n");
}

void ControlPanel::changeApplyButton() {
  printf("Virtual:changeApplyButton()!\n");
}

void ControlPanel::doInfoOkay() {
  printf("Virtual:doInfoOkay()\n");
}
